### PR TITLE
Replace jQuery with HTTP package

### PR DESCRIPTION
**Pull request by jehartzog**
I moved over this [PR](https://github.com/meteorhacks/kadira/pull/236) by @gbhrdt to this repo, would very much like to no longer include jQuery v1.11.10 in my Meteor bundle. Thank you!

### CODE REVIEW

**Comment by skirunman** [comment]
@abernix @timbotnik Not sure who is maintaining this package, but we were analyzing our production build and saw that jQuery had snuck back in adding 100kb to the image size. As a paying user of Galaxy Pro with Meteor APM we'd like to request that this PR get accepted to remove this unneeded dependency. This is time critical for us as we are just about to release a new production version of our app. Without this PR we will have to fork and support our own package. Thanks!

**Review by abernix — APPROVED** [review]

**Comment by timbotnik** [comment]
@jehartzog @skirunman @gbhrdt we've merged this PR & published v3.1.0, which includes 1 bug fix for the "Content-Type" header on top of this PR.  https://github.com/meteor/meteor-apm-agent/commit/26973ad42d08083a974e5c274c003dc8ce8d2190 Please test and verify that everything works as expected ;-)

**Comment by jehartzog** [comment]
@timbotnik I've pushed this to my Galaxy app and it looks good, APM data is still coming in.

I was unsuccessful in removing the jQuery Meteor package from my bundle, turns out I had created this PR before I had updated to use the handy [`meteor list --tree`](https://github.com/meteor/meteor/pull/8936) command and didn't catch that jQuery was still being snuck into my bundle by [`accounts-ui`](https://github.com/meteor/meteor/tree/devel/packages/accounts-ui) [here](https://github.com/meteor/meteor/blob/devel/packages/accounts-ui-unstyled/package.js#L8) and [here](https://github.com/meteor/blaze/blob/master/packages/blaze/package.js#L9), but that's a battle for me to work another day.

Thanks again for accepting the PR.

**Comment by mariusglauer** [comment]
Thanks for merging! One step further to make our meteor bundle smaller and the web faster.

**Comment by skirunman** [comment]
Things look to be working for us on Galaxy with APM. Thanks guys for being so responsive, great job!

**Pull request merged**
