### PR TITLE
remove unnecessary logging

### PR DESCRIPTION
**Pull request by harrisonhunter**
fixes this issue in original kadira package: https://github.com/meteorhacks/kadira/issues/174
inspired by this pr: https://github.com/lmachens/kadira/commit/910baca744b5cb6880551fd3a1cb9aa04aea885d

### CODE REVIEW

**Comment by mcfoton** [comment]
How do we make sure that the logging is actually _unnecessary_? Looks like it warns about something that went wrong.

**Comment by lynchem** [comment]
We have been having this since updating the core meteor package from 1.8.2 -> 1.8.4 . We raised an issue  [here](https://github.com/meteor/meteor/issues/9730) but it was closed very quickly so unlikely we'll get a response. So we're still not sure if this is benign or not.

**Comment by tcastelli** [comment]
UPDATE: After even more tests, we can see that now instead of "dbend" events , "async" events are received sometimes when calling methods or publications. This could be then related to switching the core part of meteor package to use Promises. https://github.com/meteor/meteor/blob/573f14f171251d475be0d590a72b0f2ce94a35b2/packages/meteor/dynamics_nodejs.js#L57

I don't know exactly how this could be adressed (or if it can just be ignored), but it would be helpful if benjamn could give us a hint about the possible side-effects of using promises there (in terms of kadira).

**Comment by alanning** [comment]
I would love to find a resolution for this.  These Kadira endevents are polluting our logs.  Actually costs us money since we use a 3rd-party log aggregator.

**Comment by abasille** [comment]
Any news about this PR?

**Comment by lynchem** [comment]
@abasille - They reverted the change in the meteor core package which was causing most of it (at least for us). I'm still seeing it in one project (occasionally) whereas it's gone from the one which prompted us to open the issue initially. 
So yeah, not sure if they'll merge this or not.

**Comment by abasille** [comment]
Thank you @lynchem for your feedback. With meteor@1.6.1.1, I'm still having around 4 logs ("Kadira endevent forced complete") per minute. Not sure it's better than with previous Meteor version. The problem is that I have not spent time to identify the origin of this log. So I don't know if the issue is in my code or in the Meteor core.

**Comment by alanning** [comment]
We're still seeing this in our logs, Meteor v1.6.1.1, about 3 per minute when relatively idle.  We originally thought it was tied to using the publishComposite package but we saw some reports of it happening to people who don't use that package so didn't think it was worth pursuing that.

**Comment by lynchem** [comment]
Oh! That's a lot. We're at 1 every few hours. It might be worth opening a support ticket with them if either of you use Galaxy?

**Comment by alanning** [comment]
Since its pub/sub its relative to use case/load.  I submitted a ticket to Galaxy when it first started and they said (rightly so) its a Meteor thing so they aren't in a position to help.  That was back around the time of your first github issue [here](https://github.com/meteor/meteor/issues/9730).

Recently they pointed me to this ticket so that was nice of them.  :-)  (We got bit by the node/meteor/galaxy Seg fault issue so they noticed our log pollution.)

**Review by benjamn — APPROVED** [review]

**Pull request merged**
